spring:
    profiles:
        active: dev

---
#Spring配置
spring:
  profiles: dev
  application:
    name: SpringCloud-config-dept
server:
  port: 8002

#mybatis配置
mybatis:
  type-aliases-package: com.mou.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#Spring配置
spring:
  application:
    name: SpringCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002 # 修改Eureka默认描述信息,重点，和client平级
    prefer-ip-address: true # true访问路径可以显示IP地址

#info配置
info:
  app.name: moujing-springcloud
  company.name: www.mou.com
  
---
#Spring配置
spring:
  profiles: dev
  application:
    name: SpringCloud-config-dept
server:
  port: 8002

#mybatis配置
mybatis:
  type-aliases-package: com.mou.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#Spring配置
spring:
  application:
    name: SpringCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002 # 修改Eureka默认描述信息,重点，和client平级
    prefer-ip-address: true # true访问路径可以显示IP地址

#info配置
info:
  app.name: moujing-springcloud
  company.name: www.mou.com