spring:
    profiles:
        active: dev
        

---
#Spring配置
spring:
  profiles: dev
  application:
    name: SpringCloud-config-eureka
server:
  port: 7001

#Eureka
eureka:
  instance:
    hostname: eureka7001.com       #Eureka服务端示例的名字
  client:
    register-with-eureka: false     # 是否将自己注册到Eureka服务器中，本身是服务器，无需注册
    fetch-registry: false             # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个defaultZone地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
spring:
  profiles: test
  application:
    name: SpringCloud-config-eureka
server:
  port: 7002

#Eureka
eureka:
  instance:
    hostname: eureka7002.com       #Eureka服务端示例的名字
  client:
    register-with-eureka: false     # 是否将自己注册到Eureka服务器中，本身是服务器，无需注册
    fetch-registry: false             # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个defaultZone地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/